### ISSUE TITLE
Legende(n) je Ebene und ggf. Teilmodell

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/mii-architecture#11]
Prüfen, ob alle TM Legende, Überschrift, Beschreibung etc. haben.
Ggf. diese erstellen.

### Status von Anwendungssystemen:
- Zugehörigkeit zu einer OE -> Farbe
   -  DIZ: grün
   - FDPG: orange
   - usw. siehe FE TM 01. Overview
- Required / exemplary or optional (bezogen auf das TM!) -> Farbintensität
   - dunkel: required
   - hell: exemplary / optional
- Status der Einführung (nur bei Required Elementen) -> Schrift
   - Fett: vollständig eingeführt und produktiv
   - Normal: z.T. eingeführt oder keine vollständigen Informationen
   - Kursiv: in Planung

**Diskussion in der TF üS (25.04.2024):** Ja, passt! Umsetzen und in einer der nächsten Sitzungen vorstellen.

### ToDo:
- [x] Legende (je Ebene) designen im Modell
- [x] Legende in alle TM/Ebenen einfügen
- [x] vorhandene Elemente entspr. der Legende einfärben/Schrift ändern etc. -> TF üS
