### ISSUE TITLE
[EPIC] Gesamtarchitektur v2

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/mii-architecture#8]
### Auswahl für v2
- [x] Terminologieserver:
  - Status quo:
    - [x] Ontoserver
    - [x] RZ: Köln
    - Nutzung aktuell durch 
      - [x] FDPG (Deploy: Python-Script "[FHIR Ontologie Generator](https://github.com/medizininformatik-initiative/fhir-ontology-generator)" (git), läuft auf Entwicklungsrechner)
      - [x] einzelne DIZ: Terminologieserver in TM DIC detailed hinzugefügt.
    - [x] TM DIC: 
      - [x] Terminologieserver als opt. Anw.sys anlegen (analog MDR)
      - [x] MDR ebenfalls optional
      - [x] TM DIZ Layout finalisieren
- [x] FDPG:Machbarkeit/Datenselektion aktualisieren?
  - [x] Aktin entfernen -> archiviert (99.*)
  - [x] Datenselektion/Extraktion einfügen
    - [Torch](https://confluence.imi.med.fau.de/pages/viewpage.action?pageId=287535598), analog zu Flare -> V2
- [ ] TM DIZ (Konsens? Abnahme?)
- [x] Finalisierung ST+Max+X
- [ ] Update Wiki
- [ ] Update Dokumente?
- [ ] Vorstellung TF üS
- [ ] Vorstellung AG IOP?

### Themen
- Teilmodell MII DIZ: Harmonisierung DIZ-Modell aus DFG-Projekt vs. Teilmodell DIZ Gesamtarchitektur vs. NUM-DIZ Zielbild,  [TF üS medizininformatik-initiative/mii-architecture#3](https://github.com/medizininformatik-initiative/PM-TF-Uebergreifende-Schnittstellen/issues/3)
- Gesamtarchitektur v2
  - Zu welche Teilmodellen liegt (neues) Material vor?
  - Welche Teilmodelle sind veraltet, z.B. AKTIN und wie gehen wir damit um? Löschen, als veraltet markieren?
  - Welche Teilmodelle priorisieren wir? Was modellieren wir bis wann?
    - TM Testinfrastruktur: Welche Komponenten gibt es? Wie erfolgt der Zugriff? Links für Zugriff und auf die Doku, Repos, etc. hinterlegen
  - Wie können bestehende Teilmodelle optimiert werden, z.B. hinsichtlich Verständnis, Lesbarkeit, Granularität, Vollständigkeit, usw.?
  - Modellieren wir IST oder SOLL Zustände, oder beides? Wie genau machen bzw. kennzeichnen wir das?
- [NUM-DIZ Zielbild](https://tmfev.sharepoint.com/:p:/r/sites/tmf/mi-i/_layouts/15/Doc.aspx?sourcedoc=%7B5C5F68BE-AD17-4128-873E-D7009BE90B88%7D&file=DIZ-Zielbild_V02.pptx&action=edit&mobileredirect=true) als SOLL-Zustand modellieren?
- TM: Datasharing?
- Updates FDPG(+, Community), DSF, usw., die aktualisiert oder aufgenommen werden sollten?

- NUM-Dashboard in neues Teilmodell aufnehmen -> v3
- Terminologie-Server (Test) -> v3
- TM Terminologie-Server -> v3
  - Wo befindet sich das Material dazu? -> [online-Modelle](https://s.icepanel.io/ligXOqfVN71sfk/tBpQ) (JW)
  - Eigenes Teilmodell?
  - In welchem TM detailliert? 
  - In welchem TM grob?
  - soll abgelöst werden "Termite" -> V3
- FDPG (Lokales Deployment) -> v3
- FDPG Process: Data Transfer Availability -> v3

- Begriffe kläre: https://tmfev.sharepoint.com/:x:/r/sites/tmf/mi-i/_layouts/15/Doc.aspx?sourcedoc=%7B9E0F5E59-302F-4911-92FF-D729C137E1E4%7D&file=MII_Verwendete_Begriffe_Elemente.xlsx&action=default&mobileredirect=true

- Pseudonymisierung / Aggregation -> V3
   - FTS (Teile von FTS + Torch) / Pseudonymizer

Siehe [EPIC] Gesamtarchitektur v2 [#17](https://github.com/medizininformatik-initiative/PM-TF-Uebergreifende-Schnittstellen/issues/17)
(Wurde aus versehen in das Repo [PM-TF-Uebergreifende-Schnittstellen](https://github.com/medizininformatik-initiative/PM-TF-Uebergreifende-Schnittstellen) verschoben, was sich nicht rückgängig machen lässt.)

- Versionen zukünftig halbjährlich (Übernahme der bis dahin etablierten Entwicklungen, Konsolidierung)
